name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/staging/etc.)"
        required: true
        default: "dev"

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::061039798341:role/github-actions-plugfolio-role
          aws-region: us-east-1
          role-session-name: GitHubActionsPlugfolio

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
